[package]
name = "ffi_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
winit = "0.23.0"
raw-window-handle = "0.3.3"